name: Build binaries and upload artifacts

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/**
      - "*.nimble"
      - src/**

jobs:
  build-linux-win:
    runs-on: ubuntu-18.04
    env:
      NIMVER: "1.2.6"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache nim, nimble, sqlite3
        uses: actions/cache@v2
        id: cache
        with:
          key: build-${{ runner.os }}-nim-${{ env.NIMVER }}
          path: |
            nim
            ~/.nimble
            sqlite3.*
            winsqlite3.*

      - name: Install apt packages
        run: sudo apt-get install -y --no-install-recommends binutils musl-tools mingw-w64

      - name: Download and setup nim, nimble
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir nim
          cd nim
          wget https://nim-lang.org/download/nim-$NIMVER-linux_x64.tar.xz
          tar xf nim-$NIMVER-linux_x64.tar.xz

      - name: Install nimble packages
        run: PATH="$PWD/nim/nim-$NIMVER/bin:$PATH" nimble install -y

      - name: Compile for Windows
        # on Ubuntu the binary has no .exe extension for some reason
        run: |
          PATH="$PWD/nim/nim-$NIMVER/bin:$PATH" VERSION=`git rev-parse --short HEAD` nimble win
          mv nwn_sqlite nwn_sqlite.exe
          ls -l nwn_sqlite.exe
          file nwn_sqlite.exe

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: nwn_sqlite.windows.amd64.static
          path: nwn_sqlite.exe

      - name: Compile debug build for Windows
        run: |
          PATH="$PWD/nim/nim-$NIMVER/bin:$PATH" VERSION=`git rev-parse --short HEAD` nimble build -d:mingw --passL:-static --dynlibOverrideAll --passL:winsqlite3.a nwn_sqlite
          mv nwn_sqlite nwn_sqlite-debug.exe
          ls -l nwn_sqlite-debug.exe
          file nwn_sqlite-debug.exe

      - name: Upload Windows debug artifact
        uses: actions/upload-artifact@v2
        with:
          name: debug.nwn_sqlite.windows.amd64.static
          path: nwn_sqlite-debug.exe

      - name: Compile for Linux
        run: |
          PATH="$PWD/nim/nim-$NIMVER/bin:$PATH" VERSION=`git rev-parse --short HEAD` nimble musl
          ls -l nwn_sqlite
          file nwn_sqlite

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v2
        with:
          name: nwn_sqlite.linux.amd64.static
          path: nwn_sqlite

      - name: Compile debug build for Linux
        run: |
          PATH="$PWD/nim/nim-$NIMVER/bin:$PATH" VERSION=`git rev-parse --short HEAD` nimble build --gcc.exe:musl-gcc --gcc.linkerexe:musl-gcc --passL:-static --dynlibOverrideAll --passL:sqlite3.a nwn_sqlite
          mv nwn_sqlite nwn_sqlite-debug
          ls -l nwn_sqlite-debug
          file nwn_sqlite-debug

      - name: Upload Linux debug artifact
        uses: actions/upload-artifact@v2
        with:
          name: debug.nwn_sqlite.linux.amd64.static
          path: nwn_sqlite-debug

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache nimble, sqlite3
        uses: actions/cache@v2
        id: cache
        with:
          key: build-${{ runner.os }}
          path: |
            ~/.nimble
            sqlite3.*
            macsqlite3.*

      - name: Install nim
        run: brew install nim

      - name: Install nimble packages
        run: nimble install -y

      - name: Compile for macOS
        run: |
          VERSION=`git rev-parse --short HEAD` nimble macos
          ls -l nwn_sqlite
          file nwn_sqlite

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v2
        with:
          name: nwn_sqlite.macos.amd64
          path: nwn_sqlite

      - name: Compile debug build for macOS
        run: |
          VERSION=`git rev-parse --short HEAD` nimble build --dynlibOverride:sqlite3 --passL:macsqlite3.a nwn_sqlite
          ls -l nwn_sqlite
          file nwn_sqlite

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v2
        with:
          name: debug.nwn_sqlite.macos.amd64
          path: nwn_sqlite
